Commit for Refactoring of code. #11
Muhib007dev/CoronaApiInJava pull request #12
Opened 2021-10-03 07:03 UTC by mihirterna

Moved common methods into single static helper class, for better reusability. Formatted java classes for better readability. Tested every changes in local. Working fine as expected.

2021-10-03 09:50 UTC, mihirterna commented
Please add label hacktoberfest-accepted for this PR. Thanks.

2021-10-03 10:00 UTC, Muhib007dev commented
Can you add one more package of service layer and move the business logic from controller into that package. Also try to refactor the variable names as well.

2021-10-04 06:13 UTC, mihirterna commented
Ok, can you please give example on service layer abstraction ?

2021-10-04 08:29 UTC, Muhib007dev commented
In short, I want to make it more readable and manageable, according to the standards.

2021-10-04 12:16 UTC, Muhib007dev requested changes

2021-10-04 12:16 UTC, Muhib007dev commented on src/main/java/com/coronaapi/coronarestapi/controller/WebController.java
>  		}
For example, we can move all this code into the package of the service layer.

2021-10-04 12:58 UTC, mihirterna commented on src/main/java/com/coronaapi/coronarestapi/controller/WebController.java
>  		}
Thanks for review, Have committed new changes, please review.

2021-10-06 01:16 UTC, Muhib007dev commented on src/main/java/com/coronaapi/coronarestapi/controller/WebController.java
>  		}
sure. thank you.

2021-10-07 02:20 UTC, merged

2021-10-07 02:21 UTC, Muhib007dev commented
Thank you for the contribution.

2021-10-07 02:38 UTC, mihirterna commented
Thanks  @Muhib007dev .
Can you please add hacktoberfest-accepted label now, since PR is accepted. Thanks